### ISSUE TITLE
(bug) macOS Application does not read-out CD TEXT

### ISSUE THREAD

**Issue by DaveFlashNL** [Jo2003/cd2netmd_gui#3]
just burned a test cd, but the application is not reading out the cd text, which is present on the disc, I checked through terminal `drutil cdtext` command:
![Schermafbeelding 2022-02-07 om 16 24 25](https://user-images.githubusercontent.com/72280178/152817907-0a9c969e-6bf1-4c62-bad6-63939c484a9f.png)
![Schermafbeelding 2022-02-07 om 16 24 47](https://user-images.githubusercontent.com/72280178/152817928-7985e94c-abef-4583-bde4-654ed86b3043.png)

**Comment by Jo2003** [comment]
Does pressing Re-load CD button help?

**Comment by DaveFlashNL** [comment]
> Does pressing Re-load CD button help?

nope, it does not, it does reload the cd yes, but sans any meta data

**Comment by Jo2003** [comment]
OK, I tested it on my VM also with no success. Maybe there is something wrong with the brew version of libcdio.

**Comment by Jo2003** [comment]
Even newest version of libcdio can't read CD-Text on Mac. So it looks like we stick to this currently.

**Comment by DaveFlashNL** [comment]
you can get cd-text through macOS terminal command, 'drutil cdtext', is that something you can add in the background, that your app on macOS does a bash script, output will then be in xml format I believe.

**Comment by Jo2003** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} If I find the time I first will look at libcdio for the problem. If there is no way I may try the command line tool. Currently drag and drop has priority 1.                                                                                                                                             Gesendet über BlackBerry Hub+ Posteingang für Android                                                                                                                                                                           Von: ***@***.***: 20. Februar 2022 13:51An: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [Jo2003/cd2netmd_gui] (bug) macOS Application does not read-out CD TEXT (Issue #3)  
you can get cd-text through macOS terminal command, 'drutil cdtext', is that something you can add in the background, that your app on macOS does a bash script, output will then be in xml format I believe.

**Comment by DaveFlashNL** [comment]
very good, here's an example output of drive util in terminal:

`drutil cdtext 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>Properties</key>
		<dict>
			<key>DRCDTextCFStringEncodingKey</key>
			<integer>66049</integer>
			<key>DRCDTextCharacterCodeKey</key>
			<integer>0</integer>
			<key>DRCDTextCopyrightAssertedForNamesKey</key>
			<integer>0</integer>
			<key>DRCDTextCopyrightAssertedForSpecialMessagesKey</key>
			<integer>0</integer>
			<key>DRCDTextCopyrightAssertedForTitlesKey</key>
			<integer>0</integer>
			<key>DRCDTextLanguageKey</key>
			<string></string>
			<key>DRCDTextNSStringEncodingKey</key>
			<integer>5</integer>
		</dict>
		<key>Tracks</key>
		<array>
			<dict>
				<key>DRCDTextGenreCodeKey</key>
				<integer>0</integer>
				<key>DRCDTextSizeKey</key>
				<data>
				AAEcABwyABIAMAABAAAAAAAAAAOTAAAAAAAAAAAAAAAA
				AAAA
				</data>
				<key>DRCDTextTitleKey</key>
				<string>Naamloos</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Pounding, Melodic, Dramatic - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Space Kings</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Beaty, Bright - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Ergonomix</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Relaxed, Chugging - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Soundscape</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Industrial, Beaty, Lightly Dramatic - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Superlights</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Futuristic, Rhythmic, Gradually Building - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Micromusic</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Active, Pushy, Melodic - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Time Travel</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Pounding, Dramatic, Climaxing - up tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Futura City</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Lotta</string>
				<key>DRCDTextTitleKey</key>
				<string>Det vil bli bra</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Light, Optimistic, Building - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Cursor</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Bright, Optimistic, Lively - up tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>New Images</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Urgent, Beaty, Building - up tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>White Water</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Spacious, Relaxed, Flowing - slow</string>
				<key>DRCDTextTitleKey</key>
				<string>Silver Sun</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Intricate Melody With Pulsting Accomp. - up tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Crystal Power</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Smooth, Gentle, Warm, With Funkier Middle - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Night Fountains</string>
			</dict>
			<dict>
				<key>DRCDTextComposerKey</key>
				<string>David Hubbard</string>
				<key>DRCDTextPerformerKey</key>
				<string>De Wolfe Music Library</string>
				<key>DRCDTextSpecialMessageKey</key>
				<string>Cheerful, Chugging - mid tempo</string>
				<key>DRCDTextTitleKey</key>
				<string>Processor</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Vibe Tracks</string>
				<key>DRCDTextTitleKey</key>
				<string>Beat Your Competition</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Jimmy Fontanez/Media Right Productions</string>
				<key>DRCDTextTitleKey</key>
				<string>Floaters</string>
			</dict>
			<dict/>
			<dict/>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Rubber Necking</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Say Yeah</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Huma-Huma</string>
				<key>DRCDTextTitleKey</key>
				<string>Smooth Ridin</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Gypsy Dance</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Let's Do It</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Sweet as Honey</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Riot</string>
				<key>DRCDTextTitleKey</key>
				<string>Talk To Me</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Max Surla/Media Right Productions</string>
				<key>DRCDTextTitleKey</key>
				<string>Thinking Back</string>
			</dict>
			<dict>
				<key>DRCDTextPerformerKey</key>
				<string>Topher Mohr and Alex Elena</string>
				<key>DRCDTextTitleKey</key>
				<string>Venice Beach</string>
			</dict>
		</array>
	</dict>
</array>
</plist>
`

**Comment by Jo2003** [comment]
Newest version now uses drutil on Mac to read CD-Text. -> fixed!
