### ISSUE TITLE
NetMD Wizard sees all discs as write protect

### ISSUE THREAD

**Issue by hermanvsg** [Jo2003/cd2netmd_gui#8]
I'm using an Sony CMT-M3333NT (Type-S) and I get the following error:
<img width="580" alt="image" src="https://github.com/Jo2003/cd2netmd_gui/assets/98310839/421e9973-f322-444b-89f3-09d4bc949906">

**Comment by Jo2003** [comment]
Hi! Are you using Windows? Is the correct driver installed (zadig tool)? Does WebMiniDisc work? Is WebMiniDisc running while you use NetMD Wizard?

I have never tested such device. Maybe the log says a little more. Please go into settings and set the trace level to "debug". After that press the "re-load MD" button. Please attach the log to this issue!

Thanks!

**Comment by Jo2003** [comment]
Thanks for the log.
The MD isn't the issue. Communication with the device doesn't work at all. 
There is always a pipe error: 
2023-07-11 16:30:46|CRITICAL|sendCmd():358: libusb_control_transfer failed! Pipe error

Is webminidisc pro still open (or another software accessing your NetMD device?

**Comment by Jo2003** [comment]
I'll have a look at the netmd++ library. Maybe the first call of waitForSync() makes the issue. I'll attach a modified version of the dll when ready. Please test it. First I have to have a look.

**Comment by hermanvsg** [comment]
Found the issue: 
I have a Sony USB COMM driver for some reason.
<img width="167" alt="image" src="https://github.com/Jo2003/cd2netmd_gui/assets/98310839/33b390ee-7ed0-48a1-8171-2734c2075556">

After I disabled it NetMD Wizard works fine.

Great work

**Comment by Jo2003** [comment]
Nice! Thanks for posting the solution!
